### ISSUE TITLE
Size of Nav Bar is different

### ISSUE THREAD

**Issue by ANGLT12345** [Kids-Learn-Code/kidslearncode.github.io#1]
Not sure why but the formatting of the Nav Bar is different on various places

Join Us Page
<img width="819" alt="image" src="https://github.com/user-attachments/assets/afc944e6-7e7c-4cee-9dd0-ad02ea4db355">

Home Page
<img width="801" alt="image" src="https://github.com/user-attachments/assets/a2844405-4c69-4e17-8f20-149baf1a5728">

**Comment by hongyuklc** [comment]
I think some CSS is overwriting the Nav bar CSS. Give me a while to look into it
