### ISSUE TITLE
Logo Colour contrast

### ISSUE THREAD

**Issue by ANGLT12345** [Kids-Learn-Code/kidslearncode.github.io#2]
@ANGLT12345 Redo Logo for Colour Contrast

**Comment by hongyuklc** [comment]
Is it the "Kids Learn Code" or the logo itself

**Comment by ANGLT12345** [comment]
This should be for the actual logo itself, cos its currently not blending in very well

**Comment by ANGLT12345** [comment]
Wait nevermind, it looks much better now thanks @hongyuklc!
