### ISSUE TITLE
Nav Bar Issue

### ISSUE THREAD

**Issue by ANGLT12345** [Kids-Learn-Code/kidslearncode.github.io#3]
@hongyuklc Can you help to make the contact us page? Thanks!

**Comment by hongyuklc** [comment]
Done. Please wait a moment for the correct font to load on the page. If not, you can go to Guest Mode and open the Contact Us page.

**Comment by ANGLT12345** [comment]
One more thing, the Nav Bar, it looks like this. I tried fixing but doesn't work ❓ U see if u can solve!
<img width="373" alt="Screenshot 2024-11-05 at 4 40 47 PM" src="https://github.com/user-attachments/assets/4406412b-4622-454a-bafe-a82d0c0b1e8e">

**Comment by hongyuklc** [comment]
The issue has been resolved. The margin-top for the sidebar has been adjusted to accommodate the movement of the “x” button.
