### ISSUE TITLE
Side Panel Issue

### ISSUE THREAD

**Issue by ANGLT12345** [Kids-Learn-Code/kidslearncode.github.io#4]
![2024-11-05 16-48-32 High Res Screenshot](https://github.com/user-attachments/assets/cd1b5b1c-6d29-4152-965b-ab86b9823f34)
Not sure why like that on IOS phones

**Comment by ANGLT12345** [comment]
@hongyuklc Above was tested on IOS 16.2. Same issue on 17.2 but issue resolved on 18.0

**Comment by ANGLT12345** [comment]
> @hongyuklc Above was tested on IOS 16.2. Same issue on 17.2 but issue resolved on 18.0

Issue somewhat also present on Android 10.0

**Comment by hongyuklc** [comment]
This issue appears to be related to a recent CSS update that is not yet being reflected on mobile devices. This is resolved in the update. The overflow of the banner text is now indicated by “…”, ensuring that it does not obstruct the navigation bar. Additionally, the sidebar’s “x” icon has been moved down to make it more visible.
